DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS wishlists CASCADE;
DROP TABLE IF EXISTS journals CASCADE;
CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  email VARCHAR(256) NOT NULL,
  password_hash VARCHAR(512) NOT NULL
);
CREATE TABLE wishlists (
  id SERIAL PRIMARY KEY NOT NULL,
  object_name VARCHAR(256) NOT NULL,
  owner_id INTEGER NOT NULL REFERENCES users(id)
);
CREATE TABLE journals (
  id SERIAL PRIMARY KEY NOT NULL,
  object_name VARCHAR(256) NOT NULL,
  journal_entry VARCHAR(512) NOT NULL,
  date VARCHAR(256) NOT NULL,
  image_url VARCHAR(512) NOT NULL,
  owner_id INTEGER NOT NULL REFERENCES users(id)
);